name: Documentation
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
jobs:
    docs:
        name: "Build Documentation"
        runs-on: "ubuntu-latest"
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4
            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  enable-cache: true
                  cache-dependency-glob: "uv.lock"
            - name: Setup Python
              run: uv python install
            - name: Install the project
              run: uv sync --all-extras --dev
            - uses: "actions/checkout@v4"
            - uses: r-lib/actions/setup-pandoc@v1
            - name: "Install documentation requirements"
              run: |
                  ulimit -n 50000
                  uv pip install -r docs/requirements.txt
            - name: "Create documentation"
              run: sh make_docs.sh
              working-directory: ./docs
